FROM ubuntu:16.04
EXPOSE 80 443 9000

#RUN apt-get update && \
#    apt-get install -y software-properties-common\
#    python-software-properties
    
#RUN LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php 
    
RUN apt-get update && \ 
    apt-get dist-upgrade -y &&  \
    apt-get install -y \
      apache2 \
      php7.0 \
      php7.0-common \
      php7.0-cli \
      libapache2-mod-php7.0 \
      php7.0-gd \
      php7.0-json \
      php7.0-ldap \
      php7.0-mbstring \
      php7.0-mysql \
      php7.0-pgsql \
      php7.0-sqlite3 \
      php7.0-xml \
      php7.0-xsl \
      php7.0-zip \	
      php7.0-soap \
      php7.0-curl \
      php-imagick \
      php-xdebug \
      php7.0-gd \
      less \
      mysql-client \
	zip \
	unzip \
	curl \
	wget \
	git \
	sudo 

RUN ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime && dpkg-reconfigure -f noninteractive tzdata

RUN mkdir /var/www/html/qualibet

RUN php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php && \
	php composer-setup.php && php -r "unlink('composer-setup.php');"  && \
	mv composer.phar /usr/local/bin/composer
RUN  wget https://phar.phpunit.de/phpunit.phar
RUN chmod +x phpunit.phar
RUN mv phpunit.phar /usr/local/bin/phpunit
      
RUN echo "ServerName localhost" | tee /etc/apache2/conf-available/servername.conf && \
        a2enconf servername.conf 
       
RUN phpenmod mbstring      
RUN a2enmod rewrite

COPY httpd-foreground /usr/local/bin/
COPY sites-available/ /etc/apache2/sites-available
COPY apache2.conf /etc/apache2/
COPY etc/php.ini /etc/php/7.0/apache2/
COPY etc/php.ini /etc/php/7.0/cli/

RUN chmod +x /usr/local/bin/httpd-foreground

ENV APACHE_RUN_USER www-data
ENV APACHE_RUN_GROUP www-data


RUN rm -rf /etc/apache2/sites-enabled/*
RUN ln -s /etc/apache2/sites-available/* /etc/apache2/sites-enabled/. 
RUN useradd -ms /bin/bash stephen
RUN adduser stephen sudo
RUN usermod -a -G www-data stephen
WORKDIR /var/www/html/qualibet
CMD ["httpd-foreground"]
