FROM ubuntu:16.04

EXPOSE 11300

RUN apt-get update && \ 
    apt-get dist-upgrade -y &&  \
    apt-get install -y \
    beanstalkd \
    tzdata
    
RUN ln -fs /usr/share/zoneinfo/Europe/Berlin /etc/localtime && dpkg-reconfigure -f noninteractive tzdata
    
COPY startBeanstalkd.sh /usr/local/bin/startBeanstalkd

RUN chmod +x /usr/local/bin/startBeanstalkd

CMD ["startBeanstalkd"]
    
